# Generated by Django 5.2.17 on 2026-09-16 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('use_cases', models.JSONField(blank=True, default=list)),
                ('help_goals', models.JSONField(blank=True, default=list)),
                ('font_size', models.PositiveSmallIntegerField(default=18)),
                ('line_spacing', models.CharField(choices=[('normal', 'Normal'), ('relaxed', 'Relaxed'), ('wide', 'Wide')], default='relaxed', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('sepia', 'Sepia'), ('dark', 'Dark')], default='light', max_length=20)),
                ('font_family', models.CharField(default='Source Serif 4', max_length=60)),
                ('reading_width', models.CharField(default='medium', max_length=20)),
                ('preferred_ai_provider', models.CharField(blank=True, default='', max_length=40)),
                ('explanation_level', models.CharField(default='balanced', max_length=40)),
                ('preferred_language', models.CharField(default='en', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic')], max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('encrypted_key', models.TextField()),
                ('key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-updated_at'],
                'unique_together': {('user', 'provider', 'label')},
            },
        ),
    ]
